---
# tasks file for roles/django

- name: Install epel
  yum:
    name: epel-release

- name: Install policycoreutils-python
  yum:
    name: policycoreutils-python

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - python-pip
    - python-devel

- name: Upgrade pip
  shell: curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | python

- name: Upgrade setuptools
  pip:
    name: setuptools
    state: forcereinstall

- name: Django, uwsgi pip
  pip:
    name: [Django, uwsgi]

#- name: Add django user
#  user:
#    name: django
#    group: nginx
#    shell: /bin/bash
#    home: /var/www/django
#    system: yes

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/www/django
    - /etc/uwsgi/sites


#- name: Create directory
#  file:
#    path: "{{ item.path }}"
#    state: directory
#    mode: "{{ item.mode }}"
#    owner: "{{ item.owner }}"
#    group: "{{ item.group }}"
#  with_items:
#    - { path: "/var/www/django", mode: "0775", owner: "django", group: "nginx" }
#    - { path: "/etc/uwsgi/sites", mode: "0755", owner: "root", group: "root" }

- name: Django project
  shell: |
    cd /var/www/django
    touch testfile.txt
    django-admin startproject homework
    cd /var/www/django/homework
    python manage.py migrate
#  become_user: django

- name: Connect
  lineinfile:
    path: /var/www/django/homework/homework/settings.py
    regexp: '^ALLOWED_HOSTS'
    line: "ALLOWED_HOSTS = ['192.168.11.10']"
#  become_user: django

- name: Copy config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: homework.ini, dest: /etc/uwsgi/sites/homework.ini }
    - { src: uwsgi.service, dest: /etc/systemd/system/uwsgi.service }
    - { src: uwsgi.conf, dest: /etc/nginx/conf.d/uwsgi.conf }
#  notify: restart kibana




- name: Selinux add port
  shell: semanage port -a -t http_port_t -p tcp 82

- name: Uwsgi restart
  systemd:
    name: uwsgi
    state: restarted
    daemon-reload: yes
    enabled: yes

- name: Nginx restart
  systemd:
    name: nginx
    state: restarted
    enabled: yes
